name: evofill
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
dependencies:
  - python=3.13.5
  - pytorch=2.8.0+cu129
  - torchvision
  - torchaudio
  - pytorch-cuda
  - deepspeed=0.17.4
  - biopython=1.85
  - cyvcf2=0.31.1
  - pyfaidx=0.8.2
  - tqdm
  - tensorboard
  - pip
  - libstdcxx-ng
  - nccl